version: "3.9"
services:
  postgres:
    image: bitnami/postgresql:16
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: devboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: